name: test

on:
  push:
   branches:
     - master
  workflow_dispatch:
  

jobs:
  successful-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: successful step
        run: echo "This is a test workflow."